run:
  skip-dirs-use-default: false
linters-settings:
  errcheck:
    check-type-assertions: true
  lll:
    line-length: 140
    tab-width: 4
linters:
  enable:
    - govet
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoinits
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
  disable-all: true
